#!/usr/bin/env bash
# Bash scrip to install Nginx on Ubuntu machine & configure to listen@port80

apt-get update
apt-get -y install nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen     80 default_server;
    listen     [::]:80 default_server;
    root       /etc/nginx/html;
    index      index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
