#!/usr/bin/env bash
# Displays "Best School" for other indexes and "Hi" for index 9

count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
