#!/usr/bin/env bash
# Configures a container to run Nginx as the nginx user and listen on port 8080

# Change the user from www-data to nginx in the Nginx configuration file
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Change the listening port from 80 to 8080 in the Nginx configuration file
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

